language: node_js
node_js:
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8


services:
  - docker

before_install:
  - docker build -t royalpinto/centos-dummydns test/setup
  - docker run -p 49160:8080/udp -d royalpinto/centos-dummydns
