language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

compiler:
    - clang-3.6
    - g++-4.8

env:
  - CXX=clang-3.6
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8


services:
  - docker

before_install:
  - docker build -t royalpinto/centos-dummydns test/setup
  - docker run -p 49160:8080/udp -d royalpinto/centos-dummydns
